FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Создаем пользователя для безопасности
RUN addgroup -g 1001 -S nodejs
RUN adduser -S react -u 1001

# Меняем владельца файлов
RUN chown -R react:nodejs /app
USER react

# Открываем порт
EXPOSE 3001

# Команда по умолчанию
CMD ["npm", "run", "dev"]
