FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Создаем папку dist заранее и даем права
RUN mkdir -p /app/dist && chmod 777 /app/dist

# Создаем пользователя для безопасности
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nestjs -u 1001

# Меняем владельца файлов
RUN chown -R nestjs:nodejs /app
USER nestjs

# Открываем порты
EXPOSE 3000 9229

# Команда по умолчанию с очисткой dist
CMD ["sh", "-c", "rm -rf /app/dist/* && npm run start:dev"]
